theme = "Catpuccin-mocha"
client_id = "8166ec18ef904a278facb6ee006a62ac"
client_port = 8080
login_redirect_uri = "http://127.0.0.1:8989/login"
playback_format = """
{status} {track} • {artists}
{album} • {genres}
{metadata}"""
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
page_size_in_rows = 20
play_icon = ""
pause_icon = ""
liked_icon = " "
border_type = "Plain"
progress_bar_type = "Rectangle"
enable_cover_image_cache = true
cover_img_scale = 1.0
cover_img_width = 6
cover_img_length = 14
default_device = "spotify-player"
seek_duration_secs = 5
sort_artist_albums_by_type = false

[layout]
playback_window_position = "Top"
playback_window_height = 6

[layout.library]
playlist_percent = 40
album_percent = 40

[device]
name = "spotify-player"
device_type = "speaker"
volume = 70
bitrate = 320
audio_cache = true
normalization = false
autoplay = true
